services:
  web:
    build: ./frontend/
    ports:
      - "3000:3000"
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mrhat_teste'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
